#!/bin/bash

rfkill unblock bluetooth
bluetoothctl power on

get_device_mac() {
    local devices
    devices=$(bluetoothctl devices)

    if [ "$(echo "$devices" | wc -l)" -eq 1 ]; then
        MAC=$(echo "$devices" | awk '{print $2}')
    else
        select=$(echo "$devices" | awk '{print $3}' | rofi -dmenu -l 5)
        MAC=$(echo "$devices" | grep "$select" | awk '{print $2}')
    fi

    [ -z "$MAC" ] && MAC=NoDeviceFound
}

get_device_mac

connect=$(bluetoothctl info "$MAC" | grep "Connected:" | awk '{print $2}')

if [ "$connect" = "no" ]; then
    notify-send "Attempting to Connect" "$select"
    bluetoothctl connect "$MAC" || notify-send "Failed to Connect"
elif [ "$connect" = "yes" ]; then
    notify-send "Attempting to Disconnect" "$select"
    bluetoothctl disconnect "$MAC"
fi
