#!/bin/bash

if [[ $(command -v swaybg) ]]; then
DIR="$HOME/Pictures/walls"
RANDOMPIC=$(fd . "$DIR" -t f -e png -e jpg | shuf -n 1)

if [[ $(pidof swaybg) ]]; then
  pkill swaybg
fi

swaybg  -m fill -i "$RANDOMPIC"
else
notify-send  "Swaybg not installed. Please install swaybg."
fi
exit 0
